import { useState, type FormEvent } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Loader2 } from 'lucide-react';
import { motion } from 'framer-motion';
import { AuthLayout } from '@/components/auth/AuthLayout';
import { PasswordInput } from '@/components/auth/PasswordInput';
import { useAuth } from '@/services/auth';

export function Login() {
  const { signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(true); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Please enter a valid email address.'); if (password.length < 8) return setError('Password must be at least 8 characters.'); setLoading(true); try { await signIn(email, password, remember); const next = new URLSearchParams(location.search).get('next'); navigate(next?.startsWith('/') ? next : '/app', { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Invalid email or password.'); } finally { setLoading(false); } };
  return <AuthLayout><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl bg-white p-6 text-slate-900 shadow-2xl shadow-slate-950/20 sm:p-8"><div className="mb-8"><div className="mb-6 flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-500"><CheckCircle2 className="h-5 w-5" /></div><h2 className="text-2xl font-semibold tracking-tight">Welcome back</h2><p className="mt-2 text-sm text-slate-500">Sign in to continue building better systems.</p></div>{error && <div role="alert" className="mb-5 rounded-lg border border-red-100 bg-red-50 px-3 py-2.5 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="space-y-5"><label className="block text-sm font-medium text-slate-700">Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@company.com" className="mt-2 h-11 w-full rounded-lg border border-slate-200 px-3 text-sm outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/10" /></label><label className="block text-sm font-medium text-slate-700">Password<PasswordInput value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" placeholder="Enter your password" className="mt-2" /></label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2 text-slate-500"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} className="h-4 w-4 rounded border-slate-300 text-indigo-500 focus:ring-indigo-500" />Remember me</label><Link to="/forgot-password" className="font-medium text-indigo-500 hover:text-indigo-600">Forgot password?</Link></div><button disabled={loading} className="flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-slate-900 text-sm font-semibold text-white transition hover:bg-indigo-600 disabled:opacity-60">{loading && <Loader2 className="h-4 w-4 animate-spin" />}{loading ? 'Signing in...' : 'Sign In'}<ArrowRight className="h-4 w-4" /></button></form><p className="mt-7 text-center text-sm text-slate-500">Don't have an account? <Link to="/signup" className="font-semibold text-indigo-500 hover:text-indigo-600">Create account</Link></p></motion.div></AuthLayout>;
}
