import type { Diagram, DiagramNode, DiagramType } from '@/types';
import { uid } from '@/data/diagrams';

export function createNode(type: string, position: { x: number; y: number }, data?: Record<string, unknown>): DiagramNode {
  const base = {
    id: uid('node'),
    position: { x: Math.round(position.x / 24) * 24, y: Math.round(position.y / 24) * 24 },
  };
  switch (type) {
    case 'actorNode':
      return { ...base, type, data: { label: 'Actor', type: 'use-case' } };
    case 'classNode':
      return { ...base, type, data: { label: 'Class', type: 'class', attributes: ['id: int'], methods: ['method()'], ...data } };
    case 'useCaseNode':
      return { ...base, type, data: { label: 'Use Case', type: 'use-case', ...data } };
    case 'entityNode':
      return { ...base, type, data: { label: 'Table', type: 'er', fields: ['id: int (PK)'], ...data } };
    default:
      return { ...base, type: 'genericNode', data: { label: 'Step', type: 'activity', variant: 'step', ...data } };
  }
}

const TYPE_HEADINGS: Record<DiagramType, string> = {
  'use-case': 'Use Case Diagram',
  class: 'Class Diagram',
  sequence: 'Sequence Diagram',
  activity: 'Activity Diagram',
  er: 'Entity Relationship Diagram',
  state: 'State Diagram',
  component: 'Component Diagram',
  deployment: 'Deployment Diagram',
};

export function buildPlantUml(diagram: Diagram): string {
  const lines: string[] = ['@startuml', `title ${diagram.name}`, `' ${TYPE_HEADINGS[diagram.type]} generated by UMLForge`];
  
  // Create a map for O(1) node lookups instead of O(n)
  const nodeMap = new Map(diagram.nodes.map((n) => [n.id, n]));
  
  diagram.nodes.forEach((n) => {
    const label = typeof n.data.label === 'string' ? n.data.label : 'Unnamed';
    if (n.type === 'actorNode') lines.push(`actor "${label}"`);
    else if (n.type === 'useCaseNode') lines.push(`usecase "${label}"`);
    else if (n.type === 'entityNode') {
      lines.push(`entity "${label}" {`, ...(n.data.fields ?? []).map((f) => `  ${f}`), '}');
    } else if (n.type === 'classNode') {
      lines.push(`class "${label}" {`);
      (n.data.attributes ?? []).forEach((a) => lines.push(`  ${a}`));
      (n.data.methods ?? []).forEach((m) => lines.push(`  {method} ${m}`));
      lines.push('}');
    }
  });
  diagram.edges.forEach((e) => {
    const srcNode = nodeMap.get(e.source);
    const tgtNode = nodeMap.get(e.target);
    if (!srcNode || !tgtNode) return;
    const src = typeof srcNode.data.label === 'string' ? srcNode.data.label : 'Unnamed';
    const tgt = typeof tgtNode.data.label === 'string' ? tgtNode.data.label : 'Unnamed';
    lines.push(`"${src}" -- "${tgt}"${e.label ? ` : ${e.label}` : ''}`);
  });
  lines.push('@enduml');
  return lines.join('\n');
}

export function buildJson(diagram: Diagram): string {
  return JSON.stringify({ name: diagram.name, type: diagram.type, nodes: diagram.nodes, edges: diagram.edges }, null, 2);
}