import type { Diagram, DiagramNode, DiagramType } from '@/types';
import { uid } from '@/data/diagrams';

export function createNode(type: string, position: { x: number; y: number }, data?: Record<string, unknown>): DiagramNode {
  const base = {
    id: uid('node'),
    position: { x: Math.round(position.x / 24) * 24, y: Math.round(position.y / 24) * 24 },
  };
  switch (type) {
    case 'actorNode':
      return { ...base, type, data: { label: 'Actor' } };
    case 'classNode':
      return { ...base, type, data: { label: 'Class', attributes: ['id: int'], methods: ['method()'], ...data } };
    case 'useCaseNode':
      return { ...base, type, data: { label: 'Use Case', ...data } };
    case 'entityNode':
      return { ...base, type, data: { label: 'Table', fields: ['id: int (PK)'], ...data } };
    default:
      return { ...base, type: 'genericNode', data: { label: 'Step', type: 'activity', variant: 'step', ...data } };
  }
}

const TYPE_HEADINGS: Record<DiagramType, string> = {
  'use-case': 'Use Case Diagram',
  class: 'Class Diagram',
  sequence: 'Sequence Diagram',
  activity: 'Activity Diagram',
  er: 'Entity Relationship Diagram',
};

export function buildPlantUml(diagram: Diagram): string {
  const lines: string[] = ['@startuml', `title ${diagram.name}`, `' ${TYPE_HEADINGS[diagram.type]} generated by UMLForge`];
  diagram.nodes.forEach((n) => {
    if (n.type === 'actorNode') lines.push(`actor "${n.data.label}"`);
    else if (n.type === 'useCaseNode') lines.push(`usecase "${n.data.label}"`);
    else if (n.type === 'entityNode') {
      lines.push(`entity "${n.data.label}" {`, ...(n.data.fields ?? []).map((f) => `  ${f}`), '}');
    } else if (n.type === 'classNode') {
      lines.push(`class "${n.data.label}" {`);
      (n.data.attributes ?? []).forEach((a) => lines.push(`  ${a}`));
      (n.data.methods ?? []).forEach((m) => lines.push(`  {method} ${m}`));
      lines.push('}');
    }
  });
  diagram.edges.forEach((e) => {
    const src = diagram.nodes.find((n) => n.id === e.source)?.data.label;
    const tgt = diagram.nodes.find((n) => n.id === e.target)?.data.label;
    if (!src || !tgt) return;
    lines.push(`"${src}" -- "${tgt}"${e.label ? ` : ${e.label}` : ''}`);
  });
  lines.push('@enduml');
  return lines.join('\n');
}

export function buildJson(diagram: Diagram): string {
  return JSON.stringify({ name: diagram.name, type: diagram.type, nodes: diagram.nodes, edges: diagram.edges }, null, 2);
}